# Links para doações do GitHub Sponsors e outras plataformas de financiamento coletivo.

# custom: https://apprendendo.blog/
custom: https://dev.camilaloliveira.me/
github: clcmo
ko_fi: clcmo

# patreon: #
# tidelift: #
# liberapay: #
# paypal: #
# buy_me_a_coffee: #
# issuehunt: #
# community_bridge: #
# gratipay: #
# otech: #
# boosty: #
# subscribe_star: #
# gitcoin: #
# donorbox: #
