# Como obter apoio financeiro para o desenvolvimento deste projeto.
# Veja https://docs.github.com/pt/free-pro-team@latest/github/administering-a-repository/managing-repository-settings/managing-funding-for-your-repository
# para mais informações

custom: https://apprendendo.blog/
custom: https://dev.camilaloliveira.me/
github: clcmo
ko_fi: clcmo

open_collective: #
patreon: #
tidelift: #
liberapay: #
paypal: #
buy_me_a_coffee: #
issuehunt: #
community_bridge: #
gratipay: #
otech: #
boosty: #
subscribe_star: #
gitcoin: #
donorbox: #
